# using Distributed# 0.7 code
# fast_facts.jl

#################################################################

# Load all race statistical functions
@everywhere function load_stat_fn(stat::String)
    fn_table = Dict("qtime"=>(qtimes!, stat_min!),"time"=>(times!, stat_min!),"ftime"=>(ftimes!, stat_min!),
					"htime"=>(htimes!, stat_min!),"ttime"=>(ttimes!, stat_min!),"her"=>(hers!, stat_min!),
					"qe"=>(qe!, stat_min!),"he"=>(he!, stat_min!),"fe"=>(fe!, stat_min!),"se"=>(se!, stat_min!),
					"qa"=>(qe!, stat_ave!),"ha"=>(he!, stat_ave!),"fa"=>(fe!, stat_ave!),"sa"=>(se!, stat_ave!),
					"hfl"=>(hfls!, stat_ave!),"hmfl"=>(hfls!, stat_min!),
					"hml"=>(hmls!, stat_ave!),"hmml"=>(hmls!, stat_min!),
					"hops"=>(hopss!, stat_ave!),"hmops"=>(hopss!, stat_min!),
					"hcl"=>(hcls!, stat_ave!),"hMcl"=>(hmcls!, stat_min!),"hmcl"=>(hcls!, stat_min!),
					"htfl2r"=>(hfls!, stat_trend!),"htfl3r"=>(hfls!, stat_trend!),
					"htf2l2r"=>(hfls!, stat_trend!),"httl2r"=>(ttimes!, stat_trend!),
					"httl3r"=>(ttimes!, stat_trend!),"htt2l2r"=>(ttimes!, stat_trend!),
					"hthl2r"=>(htimes!, stat_trend!),"hthl3r"=>(htimes!, stat_trend!),
					"hth2l2r"=>(htimes!, stat_trend!),"htsl2r"=>(ftimes!, stat_trend!),
					"htsl3r"=>(ftimes!, stat_trend!),"hts2l2r"=>(ftimes!, stat_trend!),
					"htol2r"=>(hopss!, stat_trend!),"htol3r"=>(hopss!, stat_trend!),"hto2l2r"=>(hopss!, stat_trend!),
					"pc1st"=>(pcs!, stat_ave!),"pc2nd"=>(pcs!, stat_ave!),"pc3rd"=>(pcs!, stat_ave!),
					"pcroi"=>(pcs!, stat_ave!),"pcval"=>(pcs!, stat_ave!),"pcpay"=>(pcs!, stat_ave!),
					"pcpaw"=>(pcs!, stat_ave!),"pcave"=>(pcs!, stat_ave!),"pcmps"=>(pcs!, stat_ave!),
					"tc1st"=>(tcs!, stat_change!),"tc2nd"=>(tcs!, stat_change!),"tc3rd"=>(tcs!, stat_change!),
					"tcroi"=>(tcs!, stat_change!),"tcval"=>(tcs!, stat_change!),"tcpay"=>(tcs!, stat_change!),
					"tcpaw"=>(tcs!, stat_change!),"tcave"=>(tcs!, stat_change!),"tcmps"=>(tcs!, stat_change!),
					"dc1st"=>(dcs!, stat_change!),"dc2nd"=>(dcs!, stat_change!),"dc3rd"=>(dcs!, stat_change!),
					"dcroi"=>(dcs!, stat_change!),"dcval"=>(dcs!, stat_change!),"dcpay"=>(dcs!, stat_change!),
					"dcpaw"=>(dcs!, stat_change!),"dcave"=>(dcs!, stat_change!),"dcmps"=>(dcs!, stat_change!),
					"rc1st"=>(pcs!, stat_change!),"rc2nd"=>(pcs!, stat_change!),"rc3rd"=>(pcs!, stat_change!),
					"rcroi"=>(pcs!, stat_change!),"rcval"=>(pcs!, stat_change!),"rcpay"=>(pcs!, stat_change!),
					"rcpaw"=>(pcs!, stat_change!),"rcave"=>(pcs!, stat_change!),"rcmps"=>(pcs!, stat_change!),
					"hs1st"=>(dummy, stat_history!),"hs2nd"=>(dummy, stat_history!),"hs3rd"=>(dummy, stat_history!),
					"hsroi"=>(dummy, stat_history!),"hsval"=>(dummy, stat_history!),"hspay"=>(dummy, stat_history!),
					"hspaw"=>(dummy, stat_history!),"hsave"=>(dummy, stat_history!),"hsmps"=>(dummy, stat_history!),
					"h1st"=>(hfls!, stat_1st!))
		fn_table[stat]
end

# Load all factors functions
@everywhere function load_fact_fns()
	fn_table = Dict(99=>(
					Driver=>("__ps_DP1st"=>"Firsts","__ps_DP2nd"=>"Seconds","__ps_DP3rd"=>"Thirds",
							"__ps_DAve"=>"Ave","__ps_DROI"=>"ROI","__ps_DVal"=>"Val",
							"__ps_DPay"=>"Pay","__ps_DPayW"=>"PayW","__ps_DMPS"=>"MPS"),
					Trainer=>("__ps_TP1st"=>"Firsts","__ps_TP2nd"=>"Seconds","__ps_TP3rd"=>"Thirds",
							"__ps_TAve"=>"Ave","__ps_TROI"=>"ROI","__ps_TVal"=>"Val",
							"__ps_TPay"=>"Pay","__ps_TPayW"=>"PayW","__ps_TMPS"=>"MPS"),
					Post=>("__ps_PP1st"=>"Firsts","__ps_PP2nd"=>"Seconds","__ps_PP3rd"=>"Thirds",
							"__ps_PAve"=>"Ave","__ps_PROI"=>"ROI","__ps_PVal"=>"Val",
							"__ps_PPay"=>"Pay","__ps_PPayW"=>"PayW","__ps_PMPS"=>"MPS"),
					Horse=>("__ps_HP1st"=>"Firsts","__ps_HP2nd"=>"Seconds","__ps_HP3rd"=>"Thirds",
							"__ps_HAve"=>"Ave","__ps_HROI"=>"ROI","__ps_HVal"=>"Val",
							"__ps_HPay"=>"Pay","__ps_HPayW"=>"PayW","__ps_HMPS"=>"MPS"),
					MLine=>("__ps_MLine"=>"M_Line","__ps_MLinR"=>"M_Line"),
					Hprob=>("__ps_Hprob"=>"Hnum")),
					1=>(
					HBxTL=>("__ps_HBSTL1"=>"qtime","__ps_HBFTL1"=>"ftime","__ps_HBHTL1"=>"htime","__ps_HBTTL1"=>"ttime","__ps_HER1"=>"her"),
					HBE=>("__ps_HBQEL1"=>"NA","__ps_HBFEL1"=>"NA","__ps_HBHEL1"=>"NA","__ps_HBSEL1"=>"NA"),HBTL=>("__ps_HBTL1"=>"NA"),
					HFL=>("__ps_HFL1"=>"NA"),HML=>("__ps_HML1"=>"NA"),HOPS=>("__ps_HOPS1"=>"NA"),HCL=>("__ps_HCL1"=>"NA"),H1st=>("__ps_H1aveL1"=>"Ave"),
					PC=>("__ps_PC1st1"=>"Firsts","__ps_PC2nd1"=>"Seconds","__ps_PC3rd1"=>"Thirds","__ps_PCAve1"=>"Ave",
							"__ps_PCROI1"=>"ROI","__ps_PCVal1"=>"Val","__ps_PCPay1"=>"Pay","__ps_PCPaW1"=>"PayW","__ps_PCMPS1"=>"MPS"),
					TC=>("__ps_TC1st1"=>"Firsts","__ps_TC2nd1"=>"Seconds","__ps_TC3rd1"=>"Thirds","__ps_TCAve1"=>"Ave","__ps_TCROI1"=>"ROI",
							"__ps_TCVal1"=>"Val","__ps_TCPay1"=>"Pay","__ps_TCPaW1"=>"PayW","__ps_TCMPS1"=>"MPS"),
					DC=>("__ps_DC1st1"=>"Firsts","__ps_DC2nd1"=>"Seconds","__ps_DC3rd1"=>"Thirds","__ps_DCAve1"=>"Ave","__ps_DCROI1"=>"ROI",
							"__ps_DCVal1"=>"Val","__ps_DCPay1"=>"Pay","__ps_DCPaW1"=>"PayW","__ps_DCMPS1"=>"MPS"),
					RC=>("__ps_RC1st1"=>"Firsts","__ps_RC2nd1"=>"Seconds","__ps_RC3rd1"=>"Thirds","__ps_RCAve1"=>"Ave","__ps_RCROI1"=>"ROI",
							"__ps_RCVal1"=>"Val","__ps_RCPay1"=>"Pay","__ps_RCPaW1"=>"PayW","__ps_RCMPS1"=>"MPS"),
					HS=>("__ps_HS1st1"=>"Firsts","__ps_HS2nd1"=>"Seconds","__ps_HS3rd1"=>"Thirds","__ps_HSAve1"=>"Ave","__ps_HSROI1"=>"ROI",
							"__ps_HSVal1"=>"Val","__ps_HSPay1"=>"Pay","__ps_HSPaW1"=>"PayW","__ps_HSMPS1"=>"MPS")),
					2=>(
					HBTL=>("__ps_HBTL2"=>"NA"),
					HBxTL=>("__ps_HBSTL2"=>"qtime","__ps_HBFTL2"=>"ftime","__ps_HBHTL2"=>"htime","__ps_HBTTL2"=>"ttime","__ps_HER2"=>"her"),
					HBE=>("__ps_HBQEL2"=>"NA","__ps_HBFEL2"=>"NA","__ps_HBHEL2"=>"NA","__ps_HBSEL2"=>"NA",
							"__ps_HBQAL2"=>"NA","__ps_HBFAL2"=>"NA","__ps_HBHAL2"=>"NA","__ps_HBSAL2"=>"NA"),
					H1st=>("__ps_H1aveL2"=>"Ave"),HFL=>("__ps_HFL2"=>"NA"),HmFL=>("__ps_HmFL2"=>"NA"),HML=>("__ps_HML2"=>"NA"),HmML=>("__ps_HmML2"=>"NA"),
					HOPS=>("__ps_HOPS2"=>"NA"),HmOPS=>("__ps_HmOPS2"=>"NA"),HCL=>("__ps_HCL2"=>"NA"),HMCL=>("__ps_HMCL2"=>"NA"),HmCL=>("__ps_HmCL2"=>"NA"),
					PC=>("__ps_PC1st2"=>"Firsts","__ps_PC2nd2"=>"Seconds","__ps_PC3rd2"=>"Thirds","__ps_PCAve2"=>"Ave","__ps_PCROI2"=>"ROI",
							"__ps_PCVal2"=>"Val","__ps_PCPay2"=>"Pay","__ps_PCPaW2"=>"PayW","__ps_PCMPS2"=>"MPS"),
					TC=>("__ps_TC1st2"=>"Firsts","__ps_TC2nd2"=>"Seconds","__ps_TC3rd2"=>"Thirds","__ps_TCAve2"=>"Ave","__ps_TCROI2"=>"ROI",
							"__ps_TCVal2"=>"Val","__ps_TCPay2"=>"Pay","__ps_TCPaW2"=>"PayW","__ps_TCMPS2"=>"MPS"),
					DC=>("__ps_DC1st2"=>"Firsts","__ps_DC2nd2"=>"Seconds","__ps_DC3rd2"=>"Thirds","__ps_DCAve2"=>"Ave","__ps_DCROI2"=>"ROI",
							"__ps_DCVal2"=>"Val","__ps_DCPay2"=>"Pay","__ps_DCPaW2"=>"PayW","__ps_DCMPS2"=>"MPS"),
					RC=>("__ps_RC1st2"=>"Firsts","__ps_RC2nd2"=>"Seconds","__ps_RC3rd2"=>"Thirds","__ps_RCAve2"=>"Ave","__ps_RCROI2"=>"ROI",
							"__ps_RCVal2"=>"Val","__ps_RCPay2"=>"Pay","__ps_RCPaW2"=>"PayW","__ps_RCMPS2"=>"MPS"),
					HS=>("__ps_HS1st2"=>"Firsts","__ps_HS2nd2"=>"Seconds","__ps_HS3rd2"=>"Thirds","__ps_HSAve2"=>"Ave","__ps_HSROI2"=>"ROI",
							"__ps_HSVal2"=>"Val","__ps_HSPay2"=>"Pay","__ps_HSPaW2"=>"PayW","__ps_HSMPS2"=>"MPS")),
					3=>(
					HBTL=>("__ps_HBTL3"=>"NA"),
					HBxTL=>("__ps_HBSTL3"=>"qtime","__ps_HBFTL3"=>"ftime","__ps_HBHTL3"=>"htime","__ps_HBTTL3"=>"ttime","__ps_HER3"=>"her"),
					HBE=>("__ps_HBQEL3"=>"NA","__ps_HBFEL3"=>"NA","__ps_HBHEL3"=>"NA","__ps_HBSEL3"=>"NA",
							"__ps_HBQAL3"=>"NA","__ps_HBFAL3"=>"NA","__ps_HBHAL3"=>"NA","__ps_HBSAL3"=>"NA"),
					HSP=>("__ps_HSP3"=>"NA"),HSSP=>("__ps_HSSP3"=>"NA"),BiasT=>("__ps_BiasT3"=>"NA"),BiasE=>("__ps_BiasE3"=>"NA","__ps_BiasA3"=>"NA"),
					BiasS=>("__ps_BiasP3"=>"NA","__ps_BiasM3"=>"NA"),H1st=>("__ps_H1aveL3"=>"Ave"),
					HFL=>("__ps_HFL3"=>"NA"),HmFL=>("__ps_HmFL3"=>"NA"),HML=>("__ps_HML3"=>"NA"),HmML=>("__ps_HmML3"=>"NA"),HOPS=>("__ps_HOPS3"=>"NA"),
					HmOPS=>("__ps_HmOPS3"=>"NA"),HCL=>("__ps_HCL3"=>"NA"),HMCL=>("__ps_HMCL3"=>"NA"),HmCL=>("__ps_HmCL3"=>"NA"),
					HT=>("__ps_HTFL2R"=>"NA","__ps_HTFL3R"=>"NA","__ps_HTF2L2R"=>"NA","__ps_HTTL2R"=>"NA","__ps_HTTL3R"=>"NA","__ps_HTT2L2R"=>"NA",
							"__ps_HTHL2R"=>"NA","__ps_HTHL3R"=>"NA","__ps_HTH2L2R"=>"NA","__ps_HTSL2R"=>"NA","__ps_HTSL3R"=>"NA","__ps_HTS2L2R"=>"NA",
							"__ps_HTOL2R"=>"NA","__ps_HTOL3R"=>"NA","__ps_HTO2L2R"=>"NA"),
					HTBx=>("__ps_HTBF"=>"NA","__ps_HTBT"=>"NA","__ps_HTBH"=>"NA","__ps_HTBS"=>"NA","__ps_HTBo"=>"NA"),
					PC=>("__ps_PC1st3"=>"Firsts","__ps_PC2nd3"=>"Seconds","__ps_PC3rd3"=>"Thirds","__ps_PCAve3"=>"Ave","__ps_PCROI3"=>"ROI",
							"__ps_PCVal3"=>"Val","__ps_PCPay3"=>"Pay","__ps_PCPaW3"=>"PayW","__ps_PCMPS3"=>"MPS"),
					TC=>("__ps_TC1st3"=>"Firsts","__ps_TC2nd3"=>"Seconds","__ps_TC3rd3"=>"Thirds","__ps_TCAve3"=>"Ave","__ps_TCROI3"=>"ROI",
							"__ps_TCVal3"=>"Val","__ps_TCPay3"=>"Pay","__ps_TCPaW3"=>"PayW","__ps_TCMPS3"=>"MPS"),
					DC=>("__ps_DC1st3"=>"Firsts","__ps_DC2nd3"=>"Seconds","__ps_DC3rd3"=>"Thirds","__ps_DCAve3"=>"Ave","__ps_DCROI3"=>"ROI",
							"__ps_DCVal3"=>"Val","__ps_DCPay3"=>"Pay","__ps_DCPaW3"=>"PayW","__ps_DCMPS3"=>"MPS"),
					RC=>("__ps_RC1st3"=>"Firsts","__ps_RC2nd3"=>"Seconds","__ps_RC3rd3"=>"Thirds","__ps_RCAve3"=>"Ave","__ps_RCROI3"=>"ROI",
							"__ps_RCVal3"=>"Val","__ps_RCPay3"=>"Pay","__ps_RCPaW3"=>"PayW","__ps_RCMPS3"=>"MPS"),
					HS=>("__ps_HS1st3"=>"Firsts","__ps_HS2nd3"=>"Seconds","__ps_HS3rd3"=>"Thirds","__ps_HSAve3"=>"Ave","__ps_HSROI3"=>"ROI",
							"__ps_HSVal3"=>"Val","__ps_HSPay3"=>"Pay","__ps_HSPaW3"=>"PayW","__ps_HSMPS3"=>"MPS")),
					6=>(
					HBTL=>("__ps_HBTL6"=>"NA"),
					HBxTL=>("__ps_HBSTL6"=>"qtime","__ps_HBFTL6"=>"ftime","__ps_HBHTL6"=>"htime","__ps_HBTTL6"=>"ttime","__ps_HER6"=>"her"),
					HBE=>("__ps_HBQEL6"=>"NA","__ps_HBFEL6"=>"NA","__ps_HBHEL6"=>"NA","__ps_HBSEL6"=>"NA",
							"__ps_HBQAL6"=>"NA","__ps_HBFAL6"=>"NA","__ps_HBHAL6"=>"NA","__ps_HBSAL6"=>"NA"),
					HSP=>("__ps_HSP6"=>"NA"),HSSP=>("__ps_HSSP6"=>"NA"),BiasT=>("__ps_BiasT6"=>"NA"),BiasE=>("__ps_BiasE6"=>"NA","__ps_BiasA6"=>"NA"),
					BiasS=>("__ps_BiasP6"=>"NA","__ps_BiasM6"=>"NA"),HFL=>("__ps_HFL6"=>"NA"),HmFL=>("__ps_HmFL6"=>"NA"),HML=>("__ps_HML6"=>"NA"),
					HmML=>("__ps_HmML6"=>"NA"),HOPS=>("__ps_HOPS6"=>"NA"),HmOPS=>("__ps_HmOPS6"=>"NA"),HCL=>("__ps_HCL6"=>"NA"),
					HMCL=>("__ps_HMCL6"=>"NA"),HmCL=>("__ps_HmCL6"=>"NA"),
					PC=>("__ps_PC1st6"=>"Firsts","__ps_PC2nd6"=>"Seconds","__ps_PC3rd6"=>"Thirds","__ps_PCAve6"=>"Ave","__ps_PCROI6"=>"ROI",
							"__ps_PCVal6"=>"Val","__ps_PCPay6"=>"Pay","__ps_PCPaW6"=>"PayW","__ps_PCMPS6"=>"MPS")
							))
end
